SELECT o.OBJECT_ID, o.PARENT_ID, o.OBJECT_NAME
FROM OBJECTS o
INNER JOIN OBJECT_TYPES_PERMISSIONS otp ON otp.subject_id = o.OBJECT_TYPE_ID
AND otp.ROLE_NAME = 'CEO'
AND (otp.PERMISSION = 'r' OR otp.PERMISSION = 'rw')
AND (o.OBJECT_TYPE_ID = 3 
OR ( o.OBJECT_TYPE_ID = 
(
SELECT a.PARENT_ID FROM OBJECT_TYPES a WHERE a.OBJECT_TYPE_ID = 2
)
));
